export const ar = {
  translation: {
    "farmsAndFarmers": "المزارع والموردين",
    "common": {
      "total": "صافي الحساب",
      "typeSomething": "اكتب شي",
      "searchIn": "ابحث في ",
      "save": "حفظ",
      "close": "إغلاق",
      "edit": "تعديل",
      "show": "عرض التفاصيل"
    },
    "product": {
      "addPropduct": "إضافة منتج",
      "editPropduct": "تعديل المنتج",
      "productName": "اسم المنتج",
    },
    "menu": {
      "addToStock": "أضف إلى المخزون",
      "stock": "مخزون",
      "accounts": "حسابات",
      "addSupplier": "إضافة مورد",
      "products": "المنتجات",
      "homepage": "الصفحة الرئيسية",
      "farmsAndFarmers": "المزارع والموردين",
      "expenses": "المصروفات",
      "clients": "العملاء",
    },
    "dashboard": {
      "total": "اجمالي الخزنة",
      "products": "منتجات",
      "clients": "العملاء",
      "fridge": "ثلاجة",
      "expenses": "المصروفات",
    },
    "AddFarm": {
      "addFarm": "أضف المورد",
      "editFarm": "تعديل المورد",
      "farmName": "اسم المورد",
      "addSupplier": "إضافة مورد"
    },
    "expenses": {
      "expenseCategroy": "الصنف",
      "addExpense": "إضافة مصروف",
      "expensesName": "اسم المصروفات",
      "expensesCategoryName": "اسم فئة المصاريف",
      "addExpensesCategory": "إضافة فئة المصروفات",
      "editExpense": "تعديل المصروف"
    },
    "client": {
      "editClient": "تعديل العميل",
      "clients": "العملاء",
      "addClient": "إضافة عميل",
      "clientName": "اسم العميل",
    },
    "AddToStock": {
      "name": "اسم المورد",
      "carNumber": "رقم السياره",
      "date": "التاريخ",
      "product": "المنتج",
      "number": "العدد",
      "quantity": "الكميه",
      "discount": "الخصم",
      "netQuantity": "صافي الكمية",
      "price": "السعر",
      "payed": "مدفوع",
      "remaining": "متبقي",
      "note": "ملحوظة",
      "total": "الاجمالي",
      "save": "حفظ",
      "edit": "تعديل",
      "addProduct": "إضافة منتج جديد",
      "editProduct": "تعديل المنتج",
      "id": "#",
      "additionalPrice": "مبلغ اضافي",
      "additionalNotes": "وصف المبلغ الاضافي",
      "expenses": "المصروفات",
      "expenseDate": "تاريخ المصروف",
      "subTotal": "المبلغ",
      "value": "القيمه",
      "addExpenseOnProduct": "اضافه مصروف علي المتنج",
      "discountType": "نوع الخصم",
      "discountFlat": "ثابت",
      "discountPercentage": "نسبة مئوية",

      "created_Date": "تاريخ الإنشاء",
      "expenseName": "اسم المصروف",
      "expenseRecordNotes": "وصف المصروف",
      "expenseTypeName": "نوع المصروف",
      "paied": "مدفوع",
      "productName": "اسم المنتج",
      "expenseRecordID": "#"
    },
    "table": {
      "name": "اسم المورد",
      "carNumber": "رقم السياره",
      "date": "التاريخ",
      "supplyDate": "التاريخ",
      "product": "المنتج",
      "number": "العدد",
      "quantity": "الكميه",
      "discount": "الخصم",
      "netQuantity": "صافي الكمية",
      "price": "السعر",
      "payed": "مدفوع",
      "remaining": "متبقي",
      "note": "ملحوظة",
      "total": "الاجمالي",
      "totalRemaining": "الاجمالي",
      "save": "حفظ",
      "edit": "تعديل",
      "addProduct": "إضافة منتج جديد",
      "editProduct": "تعديل المنتج",
      "id": "#",
      "additionalPrice": "مبلغ اضافي",
      "additionalNotes": "وصف المبلغ الاضافي",
      "expenses": "المصروفات",
      "expenseDate": "تاريخ المصروف",
      "subTotal": "المبلغ",
      "value": "القيمه",
      "addExpenseOnProduct": "اضافه مصروف علي المتنج",
      "discountType": "نوع الخصم",
      "discountFlat": "ثابت",
      "discountPercentage": "نسبة مئوية",

      "created_Date": "تاريخ الإنشاء",
      "expenseName": "اسم المصروف",
      "expenseRecordNotes": "وصف المصروف",
      "expenseTypeName": "نوع المصروف",
      "paied": "مدفوع",
      "productName": "اسم المنتج",
      "expenseRecordID": "#",
      "actions": "الأوامر",
      "farmsNotes": "ملحوظة",
      "farmsName": "اسم المورد",
      "farmRecordID": "#",
    },
    "supplierTable": {
      "farmsName": "اسم المورد",
      "carNumber": "رقم السياره",
      "supplyDate": "التاريخ",
      "created_Date": "تاريخ الإنشاء",
      "product": "المنتج",
      "number": "العدد",
      "quantity": "الكميه",
      "discount": "السماح",
      "netQuantity": "صافي الكمية",
      "price": "السعر",
      "paied": "مدفوع",
      "remaining": "متبقي",
      "farmsNotes": "ملحوظة",
      "total": "الاجمالي",
      "save": "حفظ",
      "edit": "تعديل",
      "addProduct": "إضافة منتج جديد",
      "editProduct": "تعديل المنتج",
      "id": "#",
      "farmsID": "#",
      "productID": "منتج ID",
      "productName": "اسم المنتج",
      "farmRecordID": "#"
    }
  },
};
