export const ar = {
  translation: {
    "farmsAndFarmers": "المزارع والموردين",
    "common": {
      "total": "صافي الحساب",
      "typeSomething": "اكتب شي",
      "searchIn": "ابحث في ",
      "save": "حفظ",
      "close": "إغلاق",
      "edit": "تعديل",
      "show": "عرض التفاصيل"
    },
    "product": {
      "addPropduct": "إضافة منتج",
      "editPropduct": "تعديل المنتج",
      "productName": "اسم المنتج",
    },
    "routes": {
      "addToStock": "أضف إلى المخزن",
      "stock": "المخزن",
      "accounts": "الحسابات",
      "addSupplier": "إضافة مورد",
      "products": "المنتجات",
      "homepage": "الصفحة الرئيسية",
      "farmsAndFarmers": "المزارع والموردين",
      "expenses": "المصروفات",
      "clients": "العملاء",
      "employees": "الموظفين",
      "fridges": "المحطات",
      "addToFridge": "اضافه الي المحطه",
      "clientDetails": "تفاصيل العميل",
      "supplierDetails": "تفاصيل المورد",
      "fridgeDetails": "تفاصيل المحطه",
      "sendToClient": "ارسال براد",
      "employeeDetails": "تفاصيل الموظف",
      "expensesDetails": "تفاصيل المصروف",
      "login": "تسجيل الدخول"
    },
    "menu": {
      "addToStock": "أضف إلى المخزن",
      "stock": "المخزن",
      "accounts": "الحسابات",
      "addSupplier": "إضافة مورد",
      "products": "المنتجات",
      "homepage": "الصفحة الرئيسية",
      "farmsAndFarmers": "المزارع والموردين",
      "expenses": "المصروفات",
      "clients": "العملاء",
      "employees": "الموظفين",
      "fridges": "المحطات"
    },
    "dashboard": {
      "total": "اجمالي الخزنة",
      "products": "مخزون المنتجات",
      "clients": "العملاء",
      "fridge": "المحطات",
      "expenses": "المصروفات",
    },
    "AddFarm": {
      "addFarm": "أضف المورد أو المزرعة",
      "editFarm": "تعديل المورد أو المزرعة",
      "farmName": "اسم المورد أو المزرعة",
      "addSupplier": "إضافة المورد",
      "created_Date": "تاريخ الإنشاء",
    },
    "AddEmployee": {
      "addTitle": "إضافة موظف",
      "editTitle": "تعديل الموظف",
      "name": "اسم الموظف",
      "date": "تاريخ",
      "id": "#",
      "salary": "المرتب",
      "created_Date": "تاريخ الإنشاء",
      "pay": "ادفع",
      "total": "صافي الحساب",
    },
    "payForm": {
      "addTitle": "الدفع",
      "totalPay": "اجمال الدفع",
      "notes": "ملحوظة",
      "pay": "ادفع",
      "income": "استلم",
      "incomeFrom": "استلم من",
      "payTo": "ادفع ل",
      "payType1": "دفعه",
      "payType2": "نقله",
      "payType3": "تحصيل"
    },
    "PayEmployee": {
      "addTitle": "الدفع للموظف",
      "totalPay": "اجمال الدفع",
      "notes": "ملحوظة",
      "pay": "ادفع"
    },
    "expenses": {
      "expenseCategroy": "الصنف",
      "addExpense": "إضافة مصروف",
      "expensesName": "اسم المصروفات",
      "expensesCategoryName": "اسم فئة المصاريف",
      "addExpensesCategory": "إضافة فئة المصروفات",
      "editExpense": "تعديل المصروف"
    },
    "client": {
      "editClient": "تعديل العميل",
      "clients": "العملاء",
      "addClient": "إضافة عميل",
      "clientName": "اسم العميل",
      "name": "اسم العميل",
      "sendCar": "ارسال براد",
      "editCar": "تعديل براد",
      "sendTo": "ارسال",
      "date": "تاريخ الشحنه",
      "driverName": "اسم السائق",
      "carCapacity": "اجمالي الوزن",
      "deliveredToDriver": "واصل السائق",
      "payDate": "تاريخ الدفع",
      "createdDate": "تاريخ الإنشاء",
      "price": "السعر",
      "paied": "مدفوع",
      "remaining": "متبقي",
      "carTotal": "اجمالي البراد",
      "total": "الإجمالي",
      "id": "#",
      "number": "العدد",
      "quantity": "الكميه",
      "productName": "اسم المنتج",
      "description": "وصف",
      "notes": "ملحوظه",
      "payed": "مدفوع",
      "note": "ملحوظة",
      "categories": "اصناف المنتجات",
      "prodcutList": {
        "id": "#",
        "productID": "PID",
        "productName": "اسم المنتح",
        "productBoxID": "BoxID",
        "productBoxName": "اسم المنتج الصندوقي",
        "quantity": "الوزن",
        "number": "عدد الصناديق",
        "price": "السعر",
        "total": "المبلغ",
      }
    },
    "fridges": {
      "actionType": "نوع النقله",
      "in": "دخول",
      "out": "خروج",
      "created_Date": "تاريخ الإنشاء",
      "expenseName": "اسم المصروف",
      "expenseRecordNotes": "وصف المصروف",
      "expenseTypeName": "نوع المصروف",
      "paied": "مدفوع",
      "productName": "اسم المنتج",
      "expenseRecordID": "ExpRID",
      "fridges": "المحطات",
      "addTitle": "أضف المحطة",
      "addToTitle": "أضف الي المحطة",
      "editTitle": "تعديل المحطة",
      "name": "اسم المحطة",
      "fridgeName": "اسم المحطة",
      "fridgeRecordID": "FriRID",
      "description": "وصف",
      "supplyDate": "تاريخ",
      "notes": "ملحوظه",
      "actionName": "نوع العمليه",
      "carNumber": "رقم السياره",
      "date": "التاريخ",
      "product": "المنتج",
      "number": "العدد",
      "quantity": "الكميه",
      "discount": "الخصم",
      "netQuantity": "صافي الكمية",
      "price": "السعر",
      "payed": "مدفوع",
      "remaining": "متبقي",
      "total": "الإجمالي",
      "id": "#",
      "subTotal": "المبلغ",
      "value": "القيمه",
      "discountPercentage": "نسبة مئوية",
    },
    "stock": {
      "deleteQuantity": "حذف الكمية"
    },
    "AddToStock": {
      "name": "اسم المورد",
      "carNumber": "رقم السياره",
      "date": "التاريخ",
      "product": "المنتج",
      "number": "العدد",
      "quantity": "الكميه",
      "discount": "الخصم",
      "netQuantity": "صافي الكمية",
      "price": "السعر",
      "payed": "مدفوع",
      "remaining": "متبقي",
      "note": "ملحوظة",
      "total": "الإجمالي",
      "save": "حفظ",
      "edit": "تعديل",
      "addProduct": "إضافة منتج جديد",
      "editProduct": "تعديل المنتج",
      "id": "#",
      "additionalPrice": "مبلغ اضافي",
      "additionalNotes": "وصف المبلغ الاضافي",
      "expenses": "المصروفات",
      "expenseDate": "تاريخ المصروف",
      "subTotal": "المبلغ",
      "value": "القيمه",
      "addExpenseOnProduct": "اضافه مصروف علي المتنج",
      "discountType": "نوع الخصم",
      "discountFlat": "ثابت",
      "discountPercentage": "نسبة مئوية",

      "created_Date": "تاريخ الإنشاء",
      "expenseName": "اسم المصروف",
      "expenseRecordNotes": "وصف المصروف",
      "expenseTypeName": "نوع المصروف",
      "paied": "مدفوع",
      "productName": "اسم المنتج",
      "expenseRecordID": "ExpRID"
    },
    "table": {
      "empName": "اسم الموظف",
      "fridgeName": "اسم المحطة",
      "productID": "PID",
      "description": "البيان",
      "name": "اسم المورد",
      "carNumber": "رقم السياره",
      "date": "التاريخ",
      "created_Date": "تاريخ الإنشاء",
      "supplyDate": "التاريخ",
      "product": "المنتج",
      "number": "العدد",
      "quantity": "الكميه",
      "discount": "الخصم",
      "netQuantity": "صافي الكمية",
      "price": "السعر",
      "payed": "مدفوع",
      "remaining": "متبقي",
      "note": "ملحوظة",
      "notes": "ملحوظة",
      "total": "الإجمالي",
      "totalRemaining": "الإجمالي",
      "save": "حفظ",
      "edit": "تعديل",
      "addProduct": "إضافة منتج جديد",
      "editProduct": "تعديل المنتج",
      "id": "#",
      "additionalPrice": "مبلغ اضافي",
      "additionalNotes": "وصف المبلغ الاضافي",
      "expenses": "المصروفات",
      "expenseDate": "تاريخ المصروف",
      "subTotal": "المبلغ",
      "value": "القيمه",
      "addExpenseOnProduct": "اضافه مصروف علي المتنج",
      "discountType": "نوع الخصم",
      "discountFlat": "ثابت",
      "discountPercentage": "نسبة مئوية",

      "expenseName": "اسم المصروف",
      "expenseRecordNotes": "وصف المصروف",
      "expenseTypeName": "نوع المصروف",
      "paied": "مدفوع",
      "productName": "اسم المنتج",
      "expenseRecordID": "ExpID",
      "actions": "الأوامر",
      "farmsNotes": "ملحوظة",
      "farmsName": "اسم المورد",
      "farmName": "اسم المورد",
      "clientName": "اسم العميل",
      "farmRecordID": "FRID",
      "clientID": "معرف العميل",
      "empID": "معرف الموظف",
      "farmID": "معرف المورد",
      "fridgeID": "معرف التلاجه",
      "expenseID": "معرف المصروف",
      "typeID": "معرف نوع العمليه",
      "type": "نوع العمليه",

    },
    "supplierTable": {
      "description": "البيان",
      "farmsName": "اسم المورد",
      "carNumber": "رقم السياره",
      "supplyDate": "التاريخ",
      "created_Date": "تاريخ الإنشاء",
      "product": "المنتج",
      "number": "العدد",
      "quantity": "الكميه",
      "discount": "السماح",
      "netQuantity": "صافي الكمية",
      "price": "السعر",
      "paied": "مدفوع",
      "remaining": "متبقي",
      "farmsNotes": "ملحوظة",
      "total": "الإجمالي",
      "save": "حفظ",
      "edit": "تعديل",
      "addProduct": "إضافة منتج جديد",
      "editProduct": "تعديل المنتج",
      "id": "#",
      "farmsID": "FID",
      "productID": "PID",
      "productName": "اسم المنتج",
      "farmRecordID": "FRID"
    }
  },
};
