export const en = {
  translation: {
    "farmsAndFarmers": "Farms And Suppliers",
    "product": {
      "addPropduct": "Add Propduct",
      "editPropduct": "editPropduct",
      "productName": "Product Name",
    },
    "common": {
      "total": "Total",
      "typeSomething": "Type Something...",
      "searchIn": "Search in ",
      "save": "Save",
      "close": "Close",
      "edit": "Edit",
      "show": "Show details"
    },
    "menu": {
      "addToStock": "Add To Stock",
      "stock": "Stock",
      "accounts": "Accounts",
      "addSupplier": "Add Supplier",
      "products": "Products",
      "homepage": "Home",
      "farmsAndFarmers": "Farms And Suppliers",
      "clients": "Clients",
      "expenses": "Expenses",
    },
    "AddFarm": {
      "addFarm": "Add Supplier",
      "editFarm": "Edit Supplier",
      "farmName": "Supplier Name",
      "addSupplier": "Add Supplier"
    },
    "expenses": {
      "expenseCategroy": "Categroy",
      "addExpense": "Add Expenses",
      "expensesName": "Expenses Name",
      "expensesCategoryName": "Expenses Category Name",
      "addExpensesCategory": "Add Expenses Category",
      "editExpense": "Edit Expense"
    },
    "client": {
      "editClient": "Edit Client",
      "clientName": "Client Name",
      "addClient": "Add Client",
      "clients": "Clients",    
    },
    "dashboard": {
      "total": "Total",
      "products": "Products",
      "clients": "Clients",
      "fridge": "Fridge",
      "expenses": "Expenses",
    },
    "AddToStock": {
      "name": "farm Name",
      "carNumber": "Car Number",
      "date": "Date",
      "product": "Product",
      "number": "Number",
      "quantity": "Quantity",
      "discount": "Discount",
      "netQuantity": "Net Quantity",
      "price": "Price",
      "payed": "Payed",
      "remaining": "Remaining",
      "total": "Total",
      "note": "Note",
      "save": "Save",
      "edit": "Edit",
      "addProduct": "Add New Product",
      "editProduct": "Edit Product",
      "id": "ID",
      "additionalPrice": "Additional Price",
      "additionalNotes": "Additional Notes",
      "expenses": "Expenses",
      "expenseDate": "Expense Date",
      "subTotal": "Subtotal",
      "value": "value",
      "addExpenseOnProduct": "Add Expense On Product",
      "discountType": "Discount Type",
      "discountFlat": "Flat",
      "discountPercentage": "Percentage",

      "created_Date": "Created Date",
      "expenseName": "Expense Name",
      "expenseRecordNotes": "Note",
      "expenseTypeName": "Type Name",
      "paied": "Paied",
      "productName": "Product Name",
    },
    "table": {
      "name": "farm Name",
      "carNumber": "Car Number",
      "date": "Date",
      "supplyDate": "Date",
      "product": "Product",
      "number": "Number",
      "quantity": "Quantity",
      "discount": "Discount",
      "netQuantity": "Net Quantity",
      "price": "Price",
      "payed": "Payed",
      "remaining": "Remaining",
      "total": "Total",
      "totalRemaining": "Total",
      "note": "Note",
      "save": "Save",
      "edit": "Edit",
      "addProduct": "Add New Product",
      "editProduct": "Edit Product",
      "id": "ID",
      "additionalPrice": "Additional Price",
      "additionalNotes": "Additional Notes",
      "expenses": "Expenses",
      "expenseDate": "Expense Date",
      "subTotal": "Subtotal",
      "value": "value",
      "addExpenseOnProduct": "Add Expense On Product",
      "discountType": "Discount Type",
      "discountFlat": "Flat",
      "discountPercentage": "Percentage",

      "created_Date": "Created Date",
      "expenseName": "Expense Name",
      "expenseRecordNotes": "Note",
      "expenseTypeName": "Type Name",
      "paied": "Paied",
      "productName": "Product Name",
      "expenseRecordID": "ID",
      "actions": "Actions",
      "farmsNotes": "Note",
      "farmsName": "farm Name",
      "farmRecordID": "#",
    },
    "supplierTable": {
      "farmsName": "farm Name",
      "carNumber": "Car Number",
      "supplyDate": "Date",
      "created_Date": "Created Date",
      "product": "Product",
      "number": "Number",
      "quantity": "Quantity",
      "discount": "Discount",
      "netQuantity": "Net Quantity",
      "price": "Price",
      "paied": "Paied",
      "remaining": "Remaining",
      "total": "Total",
      "farmsNotes": "Note",
      "save": "Save",
      "edit": "Edit",
      "addProduct": "Add New Product",
      "editProduct": "Edit Product",
      "id": "ID",
      "farmsID": "ID",
      "productID": "Product ID",
      "productName": "Product Name",
      "farmRecordID": "#"
    }
  },
};
